import { test, expect } from "@playwright/test";
test("home has a coherent preview and no horizontal overflow", async ({ page }, testInfo) => {
 const errors:string[]=[];
 page.on("pageerror",error=>errors.push(error.message));
 await page.goto("/");
 await expect(page.getByRole("heading",{name:"A little closer to home."})).toBeVisible();
 await expect(page.getByRole("link",{name:"Find a home Rooms, flats & houses for rent"})).toBeVisible();
 await expect(page.locator("article")).toHaveCount(6);
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
 expect(overflow).toBe(false);
 expect(errors).toEqual([]);
 await page.screenshot({path:testInfo.outputPath("home.png"),fullPage:true});
});
test("search URL filters and clearing recover relevant inventory",async ({page})=>{
 await page.goto("/search?category=rent");
 await expect(page.locator("article")).toHaveCount(2);
 await page.getByLabel("Search",{exact:true}).fill("sunlit");
 await page.getByRole("button",{name:"Show results",exact:true}).click();
 await expect(page.locator("article")).toHaveCount(1);
 await expect(page).toHaveURL(/q=sunlit/);
 await page.getByRole("button",{name:"Reset",exact:true}).click();
 await expect(page.locator("article")).toHaveCount(6);
});
test("favorite and language persist across navigation",async ({page})=>{
 await page.goto("/");
 const save=page.getByRole("button",{name:"Save listing",exact:true}).first();
 await expect(save).toBeEnabled();
 await save.click();
 await page.goto("/saved");
 await expect(page.locator("article")).toHaveCount(1);
 await page.getByRole("button",{name:"Switch to Nepali",exact:true}).click();
 await expect(page.locator("html")).toHaveAttribute("lang","ne");
 await expect(page.getByRole("heading",{name:"फेरि हेर्नलायक।"})).toBeVisible();
 await page.reload();
 await expect(page.locator("html")).toHaveAttribute("lang","ne");
 await expect(page.locator("article")).toHaveCount(1);
});
test("posting validates, previews and restores a device-local text draft",async ({page},testInfo)=>{
 await page.goto("/post");
 await page.getByRole("button",{name:"Continue",exact:true}).click();
 await page.getByRole("button",{name:"Continue",exact:true}).click();
 await expect(page.getByText("Please check the highlighted details.")).toBeVisible();
 await page.getByLabel("Listing title",{exact:true}).fill("A bright rental flat");
 await page.getByLabel("Description",{exact:true}).fill("A sample flat with two rooms and a separate kitchen for preview testing.");
 await page.getByLabel("Monthly rent (NPR)",{exact:true}).fill("18000");
 await page.getByLabel("Sample locality",{exact:true}).selectOption("Birendranagar");
 await page.getByLabel("Rooms, water, bathroom & parking",{exact:true}).fill("Two bedrooms, shared water, private bathroom, no parking.");
 await page.getByLabel("Deposit (NPR; 0 if none)",{exact:true}).fill("0");
 await page.getByLabel("Your role",{exact:true}).selectOption("owner");
 await page.getByLabel("Broker fee & additional charges",{exact:true}).fill("No broker fee. Utilities excluded.");
 await page.getByRole("button",{name:"Continue",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Show it clearly."})).toBeVisible();
 await page.getByRole("button",{name:"Continue",exact:true}).click();
 await expect(page.getByRole("heading",{name:"A bright rental flat"})).toBeVisible();
 await page.getByRole("button",{name:"Save text draft",exact:true}).click();
 await expect(page.getByText("Text draft saved on this device. Photos are temporary and not saved.")).toBeVisible();
 await page.screenshot({path:testInfo.outputPath("posting-review.png"),fullPage:true});
 await page.reload();
 await page.getByRole("button",{name:"Continue",exact:true}).click();
 await expect(page.getByLabel("Listing title",{exact:true})).toHaveValue("A bright rental flat");
});
