"use client";
import { useMarket } from "@/components/market-provider";
export default function Page() {
  const { t } = useMarket();
  const sections = [
    { en: "Listing responsibilities", ne: "सूचीको जिम्मेवारी", bodyEn: "Post only items or properties you own or are authorized to represent. Use actual photos and accurate prices, condition, defects, availability and fees. Owner/broker status is self-declared. Never publish another person's phone, precise private address or documents without permission.", bodyNe: "आफ्नो वा प्रतिनिधित्व गर्न अधिकृत सामान/सम्पत्ति मात्र राख्नुहोस्। वास्तविक तस्बिर, सही मूल्य, अवस्था, कमजोरी, उपलब्धता र शुल्क दिनुहोस्। भूमिका स्वघोषित हो। अनुमति बिना अरूको फोन, निजी ठेगाना वा कागजात नराख्नुहोस्।" },
    { en: "Prohibited content", ne: "निषेधित सामग्री", bodyEn: "No stolen or counterfeit goods, weapons, drugs, regulated products, impersonation, scams, harassment or discrimination. Initial categories exclude animals, medical/financial products and house sales.", bodyNe: "चोरी, नक्कली सामान, हतियार, लागूपदार्थ, नियन्त्रित उत्पादन, झुटो पहिचान, ठगी, दुर्व्यवहार वा भेदभाव निषेध। प्रारम्भिक वर्गमा जनावर, चिकित्सा/वित्तीय उत्पादन र घर बिक्री छैनन्।" },
    { en: "Contact and privacy", ne: "सम्पर्क र गोपनीयता", bodyEn: "Your verified phone remains private unless you explicitly allow contact publication for a listing. Signed-in buyers can then reveal it, subject to limits. Inquiries share the sender's phone only when the sender chooses to. Photos are processed to remove location metadata and remain private before approval.", bodyNe: "सूचीमा सहमति नदिएसम्म प्रमाणित फोन निजी रहन्छ। सहमतिपछि सीमाभित्र प्रवेश गरेका खरिदकर्ताले देख्न सक्छन्। जिज्ञासामा पठाउनेले रोजेमा मात्र फोन दिइन्छ। तस्बिरको स्थान मेटाडाटा हटाइन्छ र स्वीकृतअघि निजी रहन्छ।" },
    { en: "Moderation and availability", ne: "समीक्षा र उपलब्धता", bodyEn: "Submissions are reviewed before publication. You may appeal a rejected or removed listing. Confirm availability to renew; listings expire after 30 days. Pause or withdraw a listing immediately to stop public contact. Edited contact consent becomes public after review.", bodyNe: "प्रकाशनअघि समीक्षा हुन्छ। अस्वीकृत वा हटाइएको सूचीको पुनरावलोकन माग्न सकिन्छ। उपलब्धता पुष्टि गरी नवीकरण गर्नुहोस्; ३० दिनपछि म्याद सकिन्छ। सार्वजनिक सम्पर्क रोक्न सूची तुरुन्त रोक्नुहोस् वा फिर्ता गर्नुहोस्। सम्पादित सम्पर्क सहमति समीक्षापछि लागू हुन्छ।" },
    { en: "Inspect before paying", ne: "भुक्तानीअघि जाँच", bodyEn: "The platform introduces buyers and sellers. It does not certify title or authenticity, provide escrow, process purchases, collect rent or deposits, or guarantee a transaction. Inspect goods/property and check relevant documents independently.", bodyNe: "प्लेटफर्मले खरिदकर्ता र विक्रेता जोड्छ। स्वामित्व, वास्तविकता वा कारोबार ग्यारेन्टी, एस्क्रो, खरिद भुक्तानी, भाडा वा धरौटी सङ्कलन गर्दैन। सामान/सम्पत्ति र कागजात स्वतन्त्र रूपमा जाँच्नुहोस्।" },
  ];
  return <main id="main" className="container section about-page"><div className="eyebrow">{t("POSTING TERMS · VERSION 2026-10-01", "सूचीका सर्त · संस्करण २०२६-१०-०१")}</div><h1>{t("Clear details. Respectful trading.", "स्पष्ट विवरण। सम्मानजनक कारोबार।")}</h1><p>{t("Prelaunch policy baseline. Before public launch, the operator must complete local legal review, publish its identity and support contact, and finalize retention.", "प्रारम्भिक नीति। सार्वजनिक सुरुवातअघि सञ्चालकले कानुनी समीक्षा, आफ्नो परिचय, सम्पर्क र भण्डारण नीति पूरा गर्नुपर्छ।")}</p>{sections.map(section => <section key={section.en}><h2>{t(section.en, section.ne)}</h2><p>{t(section.bodyEn, section.bodyNe)}</p></section>)}</main>;
}
