"use client";
import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import { ArrowLeft, Heart, MapPin, Info, ArrowRight, Copy, Check } from "lucide-react";
import { useMarket } from "./market-provider";
import { ListingCard } from "./listing-card";
import type { Listing } from "@/lib/market";
import { formatPrice } from "@/lib/market";
import { LiveContact } from "./live-contact";
export function ListingDetail({listing}:{listing:Listing}) {
 const {language,t,saved,toggleSaved,ready,inventory,savingIds,saveErrors}=useMarket();
 const [imageIndex,setImageIndex]=useState(0);
 const [copyState,setCopyState]=useState<"idle"|"copied"|"failed">("idle");
 const [message,setMessage]=useState("");
 const related=inventory.filter(item=>item.id!==listing.id&&item.category===listing.category);
 async function copy() {try{await navigator.clipboard.writeText(window.location.href);setCopyState("copied");}catch{setCopyState("failed");}}
 return <main id="main" className="container detail-page"><Link className="back-link" href={"/search?category="+listing.category}><ArrowLeft size={15}/>{t("Back to listings","सूचीमा फर्कनुहोस्")}</Link><div className="detail-heading"><div><div className="eyebrow">{listing.category==="rent"?listing.isSample===false?t("HOME FOR RENT","भाडाको घर"):t("HOME FOR RENT · SAMPLE","भाडाको घर · नमुना"):listing.category==="land"?listing.isSample===false?t("LAND FOR SALE","जग्गा बिक्री"):t("LAND FOR SALE · SAMPLE","जग्गा बिक्री · नमुना"):listing.isSample===false?t("SECONDHAND FIND","पुरानो सामान"):t("SECONDHAND FIND · SAMPLE","पुरानो सामान · नमुना")}</div><h1>{listing.title[language]}</h1><p className="detail-location"><MapPin size={16}/>{listing.locality[language]}<span>·</span>{listing.isSample===false?t("Approximate locality","सामान्य ठाउँ"):t("Illustrative location","उदाहरण ठाउँ")}</p></div><div className="detail-actions"><button className="button secondary" disabled={!ready||savingIds.includes(listing.id)} onClick={()=>toggleSaved(listing.id)} aria-pressed={saved.includes(listing.id)}><Heart size={16} fill={saved.includes(listing.id)?"currentColor":"none"}/>{savingIds.includes(listing.id)?t("Saving…","सुरक्षित हुँदैछ…"):saved.includes(listing.id)?t("Saved","सुरक्षित"):t("Save","राख्नुहोस्")}</button><button className="button secondary" onClick={copy}>{copyState==="copied"?<Check size={16}/>:<Copy size={16}/>} {copyState==="copied"?t("Copied","प्रतिलिपि भयो"):t("Share","साझा")}</button></div></div>
 {saveErrors[listing.id]&&<p className="form-error" role="alert">{t(saveErrors[listing.id],"सूची सुरक्षित भएन। फेरि प्रयास गर्नुहोस्।")}</p>}
 {copyState==="failed"&&<p role="status">{t("Copy the page address from your browser to share this preview.","पूर्वावलोकन साझा गर्न ब्राउजरको ठेगाना प्रतिलिपि गर्नुहोस्।")}</p>}
 <div className="detail-layout"><div className="detail-content"><div className="detail-photo"><Image src={listing.images?.[imageIndex]||listing.image} alt={listing.imageAlt[language]} fill unoptimized={listing.isSample===false} sizes="(max-width: 850px) 92vw, 65vw" preload style={{objectFit:"cover"}}/>{listing.isSample!==false&&<span>{t("Illustrative photograph · Not the actual property/item","उदाहरण तस्बिर · वास्तविक सम्पत्ति/सामान होइन")}</span>}</div>
  {listing.images&&listing.images.length>1&&<div className="photo-switcher">{listing.images.map((image,index)=><button key={image} className="button secondary" onClick={()=>setImageIndex(index)} aria-pressed={imageIndex===index}>{t("Photo ","तस्बिर ")}{index+1}</button>)}</div>}<div className="detail-facts">{listing.facts[language].map(fact=><span key={fact}>{fact}</span>)}</div>
  <section className="detail-section"><h2>{t("The useful details","उपयोगी विवरण")}</h2><p>{listing.description[language]}</p>{listing.details&&<dl className="cost-list">{Object.entries(listing.details).filter(([key])=>["water","bathroom","parking","availableDate","roadAccess","area","areaUnit"].includes(key)).map(([key,value])=><div key={key}><dt>{({water:t("Water","पानी"),bathroom:t("Bathroom","बाथरुम"),parking:t("Parking","पार्किङ"),availableDate:t("Available from","उपलब्ध मिति"),roadAccess:t("Road access","सडक पहुँच"),area:t("Area","क्षेत्रफल"),areaUnit:t("Area unit","क्षेत्रफल एकाइ")} as Record<string,string>)[key]}</dt><dd>{String(value)}</dd></div>)}</dl>}</section>
  {listing.condition&&<section className="detail-section"><h2>{t("Condition & known defects","अवस्था र थाहा भएका कमजोरी")}</h2><p>{listing.condition[language]}</p></section>}
  <section className="detail-section"><h2>{t("Costs, clearly stated","स्पष्ट खर्च")}</h2><dl className="cost-list"><div><dt>{listing.category==="rent"?t("Monthly rent","मासिक भाडा"):t("Asking price","माग गरिएको मूल्य")}</dt><dd>{formatPrice(listing.pricePaisa,language)}</dd></div>{listing.depositPaisa!==undefined&&<div><dt>{t("Deposit","धरौटी")}</dt><dd>{formatPrice(listing.depositPaisa,language)}</dd></div>}</dl><p>{listing.fees[language]}</p></section>
  <div className="info-panel"><Info size={20}/><p>{listing.isSample===false?t("Availability last confirmed: ","उपलब्धता अन्तिम पुष्टि: ")+new Intl.DateTimeFormat(language==="ne"?"ne-NP":"en-GB",{dateStyle:"medium",timeZone:"Asia/Kathmandu"}).format(new Date(listing.confirmedAt!)):t("A real listing will show when availability was last confirmed. This sample has no seller, verified identity or availability claim.","वास्तविक सूचीमा उपलब्धता पुष्टि मिति हुनेछ। यस नमुनामा वास्तविक विक्रेता, प्रमाणित पहिचान वा उपलब्धताको दाबी छैन।")}</p></div>
 </div>{listing.isSample===false?<LiveContact listing={listing}/>:<aside className="contact-panel"><div className="eyebrow">{t("SAMPLE ASKING PRICE","नमुना मूल्य")}</div><div className="detail-price">{formatPrice(listing.pricePaisa,language)}{listing.category==="rent"&&<span>{t("/ month","/ महिना")}</span>}</div><div className="seller-row"><span className="seller-avatar">S</span><div><strong>{listing.sellerRole[language]}</strong><span>{t("No real contact attached","वास्तविक सम्पर्क जोडिएको छैन")}</span></div></div><button className="button primary contact-action" onClick={()=>setMessage(t("This is a design preview. Seller contact will be enabled only for approved real listings after identity and consent controls are connected.","यो डिजाइन पूर्वावलोकन हो। पहिचान र सहमति प्रणाली जोडेपछि स्वीकृत वास्तविक सूचीमा मात्र सम्पर्क उपलब्ध हुनेछ।"))}>{t("About seller contact","विक्रेता सम्पर्कबारे")}<ArrowRight size={17}/></button>{message&&<p className="contact-message" role="status">{message}</p>}<div className="contact-guidance"><Info size={16}/><p>{t("Inspect before you decide. Phone verification will confirm phone control, not ownership or authenticity.","निर्णयअघि जाँच गर्नुहोस्। फोन प्रमाणीकरणले फोन नियन्त्रण मात्र पुष्टि गर्छ, स्वामित्व वा वास्तविकता होइन।")}</p></div><Link className="text-link" href="/about">{t("About this preview","पूर्वावलोकनबारे")}<ArrowRight size={14}/></Link></aside>}</div>
 {related.length>0&&<section className="related-section"><div className="section-heading"><h2>{t("More possibilities.","थप सम्भावना।")}</h2></div><div className="listing-grid">{related.map(item=><ListingCard listing={item} key={item.id}/>)}</div></section>}
 </main>;
}
